[2025-09-22T00:32:16.777+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processamento_silver.order_reviews_to_silver manual__2025-09-22T00:32:12.586757+00:00 [queued]>
[2025-09-22T00:32:16.817+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processamento_silver.order_reviews_to_silver manual__2025-09-22T00:32:12.586757+00:00 [queued]>
[2025-09-22T00:32:16.818+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-22T00:32:16.878+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): order_reviews_to_silver> on 2025-09-22 00:32:12.586757+00:00
[2025-09-22T00:32:16.926+0000] {standard_task_runner.py:60} INFO - Started process 846 to run task
[2025-09-22T00:32:16.941+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processamento_silver', 'order_reviews_to_silver', 'manual__2025-09-22T00:32:12.586757+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/processamento_silver.py', '--cfg-path', '/tmp/tmp_f0jqsho']
[2025-09-22T00:32:16.954+0000] {standard_task_runner.py:88} INFO - Job 89: Subtask order_reviews_to_silver
[2025-09-22T00:32:17.202+0000] {task_command.py:423} INFO - Running <TaskInstance: processamento_silver.order_reviews_to_silver manual__2025-09-22T00:32:12.586757+00:00 [running]> on host e833383cbb8e
[2025-09-22T00:32:17.481+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processamento_silver' AIRFLOW_CTX_TASK_ID='order_reviews_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T00:32:12.586757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-22T00:32:12.586757+00:00'
[2025-09-22T00:32:17.484+0000] {sql.py:276} INFO - Executing: CREATE SCHEMA IF NOT EXISTS silver;

DROP TABLE IF EXISTS silver.olist_order_reviews_dataset;

CREATE TABLE silver.olist_order_reviews_dataset AS
SELECT
    review_id,
    order_id,
    review_score::INTEGER,
    review_comment_title,
    review_comment_message,
    CAST(review_creation_date AS TIMESTAMP) AS review_creation_date,
    CAST(review_answer_timestamp AS TIMESTAMP) AS review_answer_timestamp
FROM bronze.olist_order_reviews_dataset;
[2025-09-22T00:32:17.567+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_db` isn't defined
[2025-09-22T00:32:17.582+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processamento_silver, task_id=order_reviews_to_silver, execution_date=20250922T003212, start_date=20250922T003216, end_date=20250922T003217
[2025-09-22T00:32:17.615+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 89 for task order_reviews_to_silver (The conn_id `***_db` isn't defined; 846)
[2025-09-22T00:32:17.691+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-22T00:32:17.759+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
